FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# make pip modern
RUN pip install --upgrade pip

# install deps (no compilers needed because 3.11 has wheels)
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501

CMD ["sh", "-c", "streamlit run dashboard/dashboard.py --server.port ${PORT:-8501} --server.address 0.0.0.0"]
